/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package robot.wvapp_veiculo;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int webview=0x7f040000;
    }
    public static final class layout {
        public static final int main=0x7f020000;
    }
    public static final class string {
        public static final int app_name=0x7f030001;
        public static final int buttonHandler=0x7f030004;
        public static final int connect=0x7f030003;
        public static final int intro=0x7f030000;
        public static final int ip_robot=0x7f030002;
    }
}
